jobs:
- deployment: deployToAppService
  displayName: 'Deploy to App Service'
  environment: ${{ parameters.envName }}

  pool:
    vmImage: Ubuntu-16.04

  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: self
          submodules: true 

        - task: AzureResourceGroupDeployment@2
          displayName: 'Deploy Web App Container (ARM)'
          inputs:
            azureSubscription: '$(azure-connection)'
            resourceGroupName: '$(res-group)'
            location: '$(location)'
            csmFile: 'azure-arm/app-service/containers/web-app-acr.json'
            csmParametersFile: 'azure-arm/app-service/containers/web-app-acr.parameters.json'
            overrideParameters: '-siteName $(appservice-name) -existingPlan $(res-group)/$(appservice-plan) -registryName $(acr-name) -registryPassword $(acr-password) -imageNameTag apps/$(app-name):latest'

        - bash: curl -S https://$(appservice-name).azurewebsites.net/ > /dev/null
          displayName: 'Check site is up'
